version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pw
      - MYSQL_DATABASE=local_db
    volumes:
      - ./mysql:/var/lib/mysql
    restart: on-failure

  phpmyadmin:
    image: wildscamp/phpmyadmin
    ports:
      - "8080:80"
    links:
      - mysql:db
    restart: on-failure

  php:
    image: wildscamp/php
    environment:
      - TIMEZONE=America/New_York
      - XDEBUG_REMOTE_HOST=host.docker.internal
      - WP_CACHE_MEMCACHED_ADDR=memcached:11211
    ports:
      - "80:80"
      - "443:443"
    working_dir: /var/www/html
    volumes:
      - ./html:/var/www/html
      - ./certificates:/etc/pki/tls
    links:
      - mysql:db
    restart: on-failure

  memcached:
      image: memcached:latest
